#!/usr/bin/perl

BEGIN { unshift @INC, '.'; }

use color;

$configfile = "./ledDisplayd.conf";
$debug = 1;


if (!$debug) {
  use Proc::Daemon;
  $pid = Proc::Daemon::Init;
  exit if $pid;
}

use Config::Simple;
$cfg = new Config::Simple($configfile);

use LWP::Simple;
use JSON;
use POSIX qw(strftime);

$subscribe = $cfg->param("subscribe");
$device = $cfg->param("device");
$mqtthost = $cfg->param("mqtthost");
$hell = $cfg->param("fullBrightness");
$dimmed = $cfg->param("dimmedBrightness");
$leds = $cfg->param("leds");

my $c = color->new(r => 3);
my $green = color->new(g => 3);

my $ledstripe = colorstripe->new(len => 144);

my $l = $ledstripe->len();
print "$l\n";

# $ledstripe->setallcolor($c);
# transmitBin($ledstripe->bin());

# $ledstripe->percent(start => 5, len => 50, 
# 	color1 => color->new(r=>5),
# 	color2 => color->new(b=>5),
# 	percent => 25);
# transmitBin($ledstripe->bin());
# sleep 2;
$ledstripe->fade(start => 5, len => 50,
	color1 => color->new(r=>5),
	color2 => color->new(b=>5));

transmitBin($ledstripe->bin());


sleep 5;

transmitBin($ledstripe->setall()->bin);

sub transmitLeds {
  my $i;
  open(O, "|mosquitto_pub -h $mqtthost -t $device -s") || die "cannot open";
  print O "ledfade ";
  for ($i=0; $i<$leds; $i++) {
    print O pack("CCC",$r[$i],$g[$i],$b[$i]);
  }
  close O || die "cannot close";
}

sub transmitBin {
  my $bin = shift;
  my $i;
  open(O, "|mosquitto_pub -h $mqtthost -t $device -s") || die "cannot open";
  print O "ledfade ";
  print O $bin;
  close O || die "cannot close";
}

