#!/usr/bin/perl

BEGIN { unshift @INC, '.'; }

use color;

$configfile = "./ledDisplayd.conf";
$debug = 1;



if (!$debug) {
  use Proc::Daemon;
  $pid = Proc::Daemon::Init;
  exit if $pid;
}

use Config::Simple;
$cfg = new Config::Simple($configfile);

use LWP::Simple;
use JSON;
use POSIX qw(strftime);

$subscribe = $cfg->param("subscribe");
$device = $cfg->param("device");
$mqtthost = $cfg->param("mqtthost");
$hell = $cfg->param("fullBrightness");
$dimmed = $cfg->param("dimmedBrightness");
$leds = $cfg->param("leds");

my $c = color->new(r => 3);
my $green = color->new(g => 3);
my $bluesky = color->new(r => 0x40, g => 0x9c, b => 0xff);

my $ledstripe = colorstripe->new(len => 144);

my $l = $ledstripe->len();
print "$l\n";


$ledstripe->percent(
 	color1 => color->new(r=>50),
 	color2 => color->new(b=>50),
	overlap => 4,
 	percent => 25)->transmit(host => $mqtthost, device => $device);

sleep 5;

$ledstripe->fill()->transmit(host => $mqtthost, device => $device);

