#!/usr/bin/perl

BEGIN { unshift @INC, '.'; }

use color;

$configfile = "./ledDisplayd.conf";
$debug = 1;



if (!$debug) {
  use Proc::Daemon;
  $pid = Proc::Daemon::Init;
  exit if $pid;
}

use Config::Simple;
$cfg = new Config::Simple($configfile);

use LWP::Simple;
use JSON;
use POSIX qw(strftime);

$subscribe = $cfg->param("subscribe");
$device = $cfg->param("device");
$mqtthost = $cfg->param("mqtthost");
$hell = $cfg->param("fullBrightness");
$dimmed = $cfg->param("dimmedBrightness");
$leds = $cfg->param("leds");

my $c = color->new(r => 3);
my $green = color->new(g => 3);
my $bluesky = color->new(r => 0x40, g => 0x9c, b => 0xff);

my $ledstripe = colorstripe->new(len => 55);

my $l = $ledstripe->len();
print "$l\n";

$ledstripe->fill( color => $c, every => 5);
transmitBin($ledstripe->bin());

sleep 2;

$ledstripe->percent(start => 0, len => 50, 
 	color1 => $bluesky,
 	color2 => color->new(b=>5),
 	percent => 25);
 transmitBin($ledstripe->bin());
 sleep 2;

transmitBin($ledstripe->fade(start => 0, len => 50)->bin());

for (my $i = 0; $i < 100; $i++) {
  transmitBin($ledstripe->shiftl()->bin());
}
sleep 1;

transmitBin($ledstripe->setall()->bin);

sub transmitBin {
  my $bin = shift;
  my $i;
  open(O, "|mosquitto_pub -h $mqtthost -t $device -s") || die "cannot open";
  print O "ledb ";
  print O $bin;
  close O || die "cannot close";
}

